# Generated by Django 3.0.6 on 2020-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20160223_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
